FROM nvidia_ros2:latest

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Create ros2_ws
RUN source /opt/ros/humble/setup.bash \
 && mkdir -p /ros2_ws/src \
 && cd ros2_ws/src
WORKDIR /ros2_ws

# Install compiler
RUN apt-get update && apt-get install -y gcc g++
ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++
RUN source ~/.bashrc

# Install python
RUN apt-get install -y python3

# Install colcon
RUN apt-get update && apt-get install -y python3-colcon-common-extensions

# Install Xacro
RUN apt-get install -y ros-humble-xacro

# Install joint state publisher
RUN apt-get install -y ros-humble-joint-state-publisher

# Compile ros2 workspace
RUN source /opt/ros/humble/setup.bash \
 && colcon build

RUN echo "source /ros2_ws/install/setup.bash" >> ~/.bashrc

WORKDIR /ros2_ws